//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export namespace Api {
	export interface ApiResponse
	{
		successful: boolean;
		message: string;
	}
	export interface ApiResponse<T> extends Api.ApiResponse
	{
		data: T;
	}
	export interface Flow
	{
		id: number;
		name: string;
	}
}
