//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export namespace Api {
  export interface ApiResponse<T = any> {
    successful: boolean;
    message: string;
    data: T
  }
	export interface Flow
	{
		id: number;
		name: string;
	}
	export interface Step
	{
		name: string;
		stepType: import('./enums').StepType;
		order: number;
		serialisedParameters: string;
	}
}
